project:
  type: website
  output-dir: docs

website:
  title: "Winthrop"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: Final Year Project
      - href: data-vis.qmd
        text: Data Visualisation
      - href: curriculum.qmd
        text: Curriculum
      - href: reflection.qmd
        text: Reflection


format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true

